language: go

go:
  - master

install:
  - go get gopkg.in/gin-gonic/gin.v1
  - go get github.com/stretchr/testify/assert

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
